algoritmo "primeiroAlgoritmo"
//=================================================================
// Algoritmo para criar a primeira mensagem.
//
// AUTOR: Lucas Alves
// Curso de Algoritmos da Plataforma Curso em Vídeo.
// Professor: Gustavo Guanabara
//=================================================================
var
   msg: caractere
inicio
  msg <- "Olá, Mundo!"
  Escreval ("mensagem: ", msg)
fimalgoritmo
